export const FILTER_GROUPS = [
  { key: 'price', label: 'Price', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sh_price_u5', label: 'Under $5' },
    { value: 'sh_price_u10', label: 'Under $10' },
    { value: 'sh_price_u20', label: 'Under $20' },
    { value: 'sh_price_u50', label: 'Under $50' },
    { value: 'sh_price_o5', label: 'Over $5' },
    { value: 'sh_price_o10', label: 'Over $10' },
    { value: 'sh_price_o20', label: 'Over $20' },
    { value: 'sh_price_o50', label: 'Over $50' },
    { value: 'sh_price_o100', label: 'Over $100' },
  ] },
  { key: 'marketCap', label: 'Market Cap', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'cap_mega', label: 'Mega ($200B+)' },
    { value: 'cap_large', label: 'Large ($10B-$200B)' },
    { value: 'cap_mid', label: 'Mid ($2B-$10B)' },
    { value: 'cap_small', label: 'Small ($300M-$2B)' },
    { value: 'cap_micro', label: 'Micro ($50M-$300M)' },
    { value: 'cap_nano', label: 'Nano (under $50M)' },
  ] },
  { key: 'pe', label: 'P/E', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_pe_profitable', label: 'Profitable (P/E > 0)' },
    { value: 'fa_pe_u15', label: 'Under 15' },
    { value: 'fa_pe_u20', label: 'Under 20' },
    { value: 'fa_pe_u30', label: 'Under 30' },
    { value: 'fa_pe_o15', label: 'Over 15' },
    { value: 'fa_pe_o30', label: 'Over 30' },
  ] },
  { key: 'forwardPE', label: 'Forward P/E', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_fpe_u15', label: 'Under 15' },
    { value: 'fa_fpe_u20', label: 'Under 20' },
    { value: 'fa_fpe_o15', label: 'Over 15' },
    { value: 'fa_fpe_o30', label: 'Over 30' },
  ] },
  { key: 'peg', label: 'PEG', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_peg_u1', label: 'Under 1' },
    { value: 'fa_peg_u2', label: 'Under 2' },
    { value: 'fa_peg_o1', label: 'Over 1' },
  ] },
  { key: 'dividendYield', label: 'Dividend Yield', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_div_none', label: 'None (0%)' },
    { value: 'fa_div_pos', label: 'Positive (>0%)' },
    { value: 'fa_div_o3', label: 'Over 3%' },
    { value: 'fa_div_o5', label: 'Over 5%' },
    { value: 'fa_div_high', label: 'Very High (>5%)' },
  ] },
  { key: 'payoutRatio', label: 'Payout Ratio', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_payoutratio_none', label: 'None (0%)' },
    { value: 'fa_payoutratio_u50', label: 'Under 50%' },
    { value: 'fa_payoutratio_o50', label: 'Over 50%' },
  ] },
  { key: 'beta', label: 'Beta', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'sh_beta_u0.5', label: 'Under 0.5' },
    { value: 'sh_beta_u1', label: 'Under 1' },
    { value: 'sh_beta_o1', label: 'Over 1' },
    { value: 'sh_beta_o1.5', label: 'Over 1.5' },
    { value: 'sh_beta_o2', label: 'Over 2' },
  ] },
  { key: 'avgVolume', label: 'Avg Volume', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sh_avgvol_u100', label: 'Under 100K' },
    { value: 'sh_avgvol_o100', label: 'Over 100K' },
    { value: 'sh_avgvol_o500', label: 'Over 500K' },
    { value: 'sh_avgvol_o1000', label: 'Over 1M' },
  ] },
  { key: 'shortInterest', label: 'Short Interest', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sh_short_low', label: 'Low (<5%)' },
    { value: 'sh_short_o5', label: 'Over 5%' },
    { value: 'sh_short_o20', label: 'Over 20%' },
    { value: 'sh_short_high', label: 'High (>20%)' },
  ] },
  { key: 'perf52w', label: '52-Week Performance', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_highlow52w_nh', label: 'New High' },
    { value: 'ta_highlow52w_nl', label: 'New Low' },
    { value: 'ta_perf_52wup', label: 'Up over past year' },
    { value: 'ta_perf_52wdown', label: 'Down over past year' },
  ] },
  { key: 'perfYtd', label: 'YTD Performance', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_perf_ytdup', label: 'Positive YTD' },
    { value: 'ta_perf_ytddown', label: 'Negative YTD' },
  ] },
  { key: 'analystRecom', label: 'Analyst Recom.', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'an_recom_strongbuy', label: 'Strong Buy' },
    { value: 'an_recom_buybetter', label: 'Buy or better' },
    { value: 'an_recom_hold', label: 'Hold' },
  ] },
  { key: 'optionable', label: 'Optionable', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sh_opt_option', label: 'Optionable' },
  ] },
  { key: 'shortable', label: 'Shortable', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sh_short_shortable', label: 'Shortable' },
  ] },
  { key: 'sector', label: 'Sector', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'sec_technology', label: 'Technology' },
    { value: 'sec_healthcare', label: 'Healthcare' },
    { value: 'sec_financial', label: 'Financial' },
    { value: 'sec_energy', label: 'Energy' },
    { value: 'sec_industrials', label: 'Industrials' },
    { value: 'sec_consumercyclical', label: 'Consumer Cyclical' },
    { value: 'sec_consumerdefensive', label: 'Consumer Defensive' },
    { value: 'sec_realestate', label: 'Real Estate' },
    { value: 'sec_basicmaterials', label: 'Basic Materials' },
    { value: 'sec_communicationservices', label: 'Communication Services' },
    { value: 'sec_utilities', label: 'Utilities' },
  ] },
  { key: 'country', label: 'Geography', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'geo_usa', label: 'USA' },
    { value: 'geo_notusa', label: 'Not USA (foreign)' },
    { value: 'geo_china', label: 'China' },
    { value: 'geo_europe', label: 'Europe' },
  ] },
  { key: 'exchange', label: 'Exchange', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'exch_nyse', label: 'NYSE' },
    { value: 'exch_nasd', label: 'NASDAQ' },
    { value: 'exch_amex', label: 'AMEX' },
  ] },
  { key: 'index', label: 'Index', category: 'descriptive', options: [
    { value: '', label: 'Any' },
    { value: 'idx_sp500', label: 'S&P 500' },
    { value: 'idx_dji', label: 'Dow Jones' },
    { value: 'idx_russell2000', label: 'Russell 2000' },
    { value: 'idx_nasdaq100', label: 'NASDAQ 100' },
  ] },
  { key: 'epsGrowthThisYear', label: 'EPS Growth This Year', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_epsyoy_pos', label: 'Positive (>0%)' },
    { value: 'fa_epsyoy_o10', label: 'Over 10%' },
    { value: 'fa_epsyoy_o20', label: 'Over 20%' },
    { value: 'fa_epsyoy_o30', label: 'Over 30%' },
  ] },
  { key: 'epsGrowthNextYear', label: 'EPS Growth Next Year', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_epsyoy1_pos', label: 'Positive (>0%)' },
    { value: 'fa_epsyoy1_o10', label: 'Over 10%' },
    { value: 'fa_epsyoy1_o20', label: 'Over 20%' },
  ] },
  { key: 'salesGrowth5y', label: 'Sales Growth (5Y)', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_sales5years_pos', label: 'Positive (>0%)' },
    { value: 'fa_sales5years_o10', label: 'Over 10%' },
    { value: 'fa_sales5years_o20', label: 'Over 20%' },
  ] },
  { key: 'roe', label: 'Return on Equity', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_roe_pos', label: 'Positive (>0%)' },
    { value: 'fa_roe_o10', label: 'Over 10%' },
    { value: 'fa_roe_o20', label: 'Over 20%' },
    { value: 'fa_roe_o30', label: 'Over 30%' },
  ] },
  { key: 'roa', label: 'Return on Assets', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_roa_pos', label: 'Positive (>0%)' },
    { value: 'fa_roa_o5', label: 'Over 5%' },
    { value: 'fa_roa_o10', label: 'Over 10%' },
    { value: 'fa_roa_o15', label: 'Over 15%' },
  ] },
  { key: 'debtEquity', label: 'Debt/Equity', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_debteq_u1', label: 'Under 1' },
    { value: 'fa_debteq_u0.5', label: 'Under 0.5' },
    { value: 'fa_debteq_low', label: 'Low (<0.1)' },
  ] },
  { key: 'grossMargin', label: 'Gross Margin', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_grossmargin_pos', label: 'Positive (>0%)' },
    { value: 'fa_grossmargin_o30', label: 'Over 30%' },
    { value: 'fa_grossmargin_o50', label: 'Over 50%' },
    { value: 'fa_grossmargin_o70', label: 'Over 70%' },
  ] },
  { key: 'operatingMargin', label: 'Operating Margin', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_opermargin_pos', label: 'Positive (>0%)' },
    { value: 'fa_opermargin_o10', label: 'Over 10%' },
    { value: 'fa_opermargin_o20', label: 'Over 20%' },
    { value: 'fa_opermargin_o30', label: 'Over 30%' },
  ] },
  { key: 'netMargin', label: 'Net Profit Margin', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_netmargin_pos', label: 'Positive (>0%)' },
    { value: 'fa_netmargin_o10', label: 'Over 10%' },
    { value: 'fa_netmargin_o20', label: 'Over 20%' },
  ] },
  { key: 'priceBook', label: 'Price/Book', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_pb_u1', label: 'Under 1' },
    { value: 'fa_pb_u3', label: 'Under 3' },
    { value: 'fa_pb_u5', label: 'Under 5' },
  ] },
  { key: 'priceSales', label: 'Price/Sales', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_ps_u1', label: 'Under 1' },
    { value: 'fa_ps_u2', label: 'Under 2' },
    { value: 'fa_ps_u5', label: 'Under 5' },
  ] },
  { key: 'priceCashFlow', label: 'Price/Cash Flow', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'fa_pc_u5', label: 'Under 5' },
    { value: 'fa_pc_u10', label: 'Under 10' },
    { value: 'fa_pc_u20', label: 'Under 20' },
  ] },
  { key: 'insiderOwn', label: 'Insider Ownership', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'sh_insiderown_low', label: 'Low (>0%)' },
    { value: 'sh_insiderown_o10', label: 'Over 10%' },
    { value: 'sh_insiderown_o30', label: 'Over 30%' },
    { value: 'sh_insiderown_high', label: 'High (>50%)' },
  ] },
  { key: 'instOwn', label: 'Institutional Ownership', category: 'fundamental', options: [
    { value: '', label: 'Any' },
    { value: 'sh_instown_low', label: 'Low (>0%)' },
    { value: 'sh_instown_o50', label: 'Over 50%' },
    { value: 'sh_instown_o90', label: 'Over 90%' },
  ] },
  { key: 'rsi', label: 'RSI (14)', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_rsi_os30', label: 'Oversold (<30)' },
    { value: 'ta_rsi_ob70', label: 'Overbought (>70)' },
    { value: 'ta_rsi_nos40', label: 'Not Oversold (>40)' },
    { value: 'ta_rsi_nob60', label: 'Not Overbought (<60)' },
  ] },
  { key: 'sma20', label: 'vs 20-Day SMA', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_sma20_pa', label: 'Price Above SMA20' },
    { value: 'ta_sma20_pb', label: 'Price Below SMA20' },
  ] },
  { key: 'sma50', label: 'vs 50-Day SMA', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_sma50_pa', label: 'Price Above SMA50' },
    { value: 'ta_sma50_pb', label: 'Price Below SMA50' },
  ] },
  { key: 'sma200', label: 'vs 200-Day SMA', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_sma200_pa', label: 'Price Above SMA200' },
    { value: 'ta_sma200_pb', label: 'Price Below SMA200' },
  ] },
  { key: 'highLow50d', label: '50-Day High/Low', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_highlow50d_nh', label: 'New High' },
    { value: 'ta_highlow50d_nl', label: 'New Low' },
    { value: 'ta_highlow50d_b0to10h', label: 'Within 10% of High' },
  ] },
  { key: 'changeToday', label: 'Change (Today)', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_change_u', label: 'Up' },
    { value: 'ta_change_u5', label: 'Up 5%+' },
    { value: 'ta_change_d', label: 'Down' },
    { value: 'ta_change_d5', label: 'Down 5%+' },
  ] },
  { key: 'relVolume', label: 'Relative Volume', category: 'technical', options: [
    { value: '', label: 'Any' },
    { value: 'ta_relvol_o1.5', label: 'Over 1.5x' },
    { value: 'ta_relvol_o2', label: 'Over 2x' },
    { value: 'ta_relvol_o3', label: 'Over 3x' },
    { value: 'ta_relvol_u1', label: 'Under 1x' },
  ] },
]
